"""
CREATE TABLE "bna_topoland" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"NOMBRE"	TEXT,
	"APELLIDO"	TEXT,
	"PIN"	INTEGER,
	"CBU"	TEXT,
	"SALDO AR$"	DEFAULT 0.0 REAL,
	"SALDO U$D"	DEFAULT 0.0 REAL,
	PRIMARY KEY("ID")
);
"""